name: raseed_systeam
description: "تطبيق رصيد لتحويل الرصيد في العراق - نظام مالي متكامل"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 # لدعم الخطوط العصرية
  intl: ^0.18.1 # لدعم العملة واللغة العربية
  http: ^1.1.0 
  url_launcher: ^6.2.5
  flutter_jailbreak_detection: ^1.1.0
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: ^5.1.0
  mobile_scanner: ^3.5.5
  permission_handler: ^10.4.0
  flutter_phone_direct_caller: ^2.1.1
  sim_data: ^0.0.2
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/images/asiacell_logo.png
    - assets/fonts/images/zain_logo.png
    - assets/fonts/images/raseed-card.png
    - assets/fonts/images/qi_card_icon.png
    

  # هنا نقوم بتعريف الخط الذي اخترته "IBM Plex Sans Arabic"
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600

          flutter_icons:
  android: true
  ios: true
  - assets/fonts/images/icon.png
  image_path: "assets/icon.png"
  min_sdk_android: 21
