name: raseed_systeam
description: "تطبيق رصيد لتحويل الرصيد في العراق - نظام مالي متكامل"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 
  intl: ^0.20.2 
  http: ^1.1.0 
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: ^5.1.0
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  flutter_phone_direct_caller: ^2.1.1
  google_mobile_ads: ^7.0.0
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # تم تصحيح المسافة هنا (يجب أن تكون على نفس مستوى flutter_test)
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/images/asiacell_logo.png
    - assets/fonts/images/zain_logo.png
    - assets/fonts/images/raseed-card.png
    - assets/fonts/images/qi_card_icon.png
    - assets/fonts/images/splash_bg.png

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600

# ==========================================
# إعدادات الأيقونة (تم تصحيح المسافة لتكون في بداية السطر)
# ==========================================
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#88E788"
  image: assets/fonts/images/splash_bg.png  
  branding: assets/fonts/images/splash_bg.png

  android_12:
    image: assets/fonts/images/splash_bg.png
    color: "#88E788"

  android: true
  ios: true
