name: raseed_systeam
description: "تطبيق رصيد لتحويل الرصيد في العراق - نظام مالي متكامل"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 # لدعم الخطوط العصرية
  intl: ^0.18.1 # لدعم العملة واللغة العربية
  http: ^1.1.0 
  url_launcher: ^6.2.5
  flutter_jailbreak_detection: ^1.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/images/asiacell_logo.png
    - assets/fonts/images/zain_logo.png

  # هنا نقوم بتعريف الخط الذي اخترته "IBM Plex Sans Arabic"
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
