name: Build Android APK (Release)

on:
  # يعمل هذا الملف عند الضغط اليدوي على الزر
  workflow_dispatch:
  
jobs:
  build:
    name: Build Optimized APK
    runs-on: ubuntu-latest

    steps:
    # 1. جلب الكود
    - uses: actions/checkout@v3

    # 2. إعداد بيئة الجافا
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. إعداد Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # 4. تنظيف عميق لبيئة العمل (لضمان خلو النسخة من الشوائب)
    - name: Deep Clean
      run: flutter clean

    # 5. تحميل المكتبات
    - name: Get Dependencies
      run: flutter pub get

    # 6. بناء ملف APK (نسخة الإنتاج الخفيفة والمقسمة)
    - name: Build Split APKs
      run: flutter build apk --release --split-per-abi

    # 7. رفع الملفات الناتجة لكي تتمكن من تحميلها
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: raseed-app-release-apks
        # سيقوم بجلب جميع النسخ المقسمة التي تم بناؤها
        path: build/app/outputs/flutter-apk/app-*-release.apk
